Add hapi config file and enable hibernate.search
uwcirg/cnics-fhir-environments pull request #3
Opened 2021-10-22 07:36 UTC by pbugni

NB, newer HAPI uses `application.yaml` in place of `hapi.properties`.

Tested locally, seems to work.

2021-10-22 07:38 UTC, pbugni commented on dev/config/hapi/application.yaml
> +      hibernate.search.backend.type: lucene
Lines #25 and #26 were commented out in source found on https://github.com/hapifhir/hapi-fhir-jpaserver-starter/blob/master/src/main/resources/application.yaml

Otherwise this file is untouched.

2021-10-22 16:03 UTC, ivan-c requested changes
Think I found a minor oversight with the switch to YAML, looks good otherwise

2021-10-22 16:03 UTC, ivan-c commented on dev/docker-compose.yaml
> +      JAVA_OPTIONS: "--spring.config.location=file:///opt/hapi.properties"
Should this be updated to reference the new YAML config, or removed entirely?

2021-11-02 18:50 UTC, pbugni commented on dev/docker-compose.yaml
> +      JAVA_OPTIONS: "--spring.config.location=file:///opt/hapi.properties"
thanks, corrected.

2021-11-02 19:39 UTC, ivan-c approved these changes

2021-11-02 20:44 UTC, merged